name: Lint test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup/pnpm

      - name: Build packages
        run: pnpm run build

      - name: Setup ESLint cache
        uses: actions/cache@v4
        with:
          path: |
            packages/eslint-config-browser/.eslintcache
            packages/eslint-config-common/.eslintcache
            packages/eslint-config-next/.eslintcache
            packages/eslint-config-node/.eslintcache
            packages/eslint-config-react/.eslintcache
            packages/eslint-config-storybook/.eslintcache
          key: ${{ runner.os }}-eslint-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-eslint-cache-

      - name: Lint Code
        run: pnpm run lint:code
