name: Lint test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup/pnpm

      - name: Lint
      - name: Build packages
        run: pnpm run build
        run: pnpm run lint:code
