name: Sort package.json

on:
  push:
    paths:
      - '**/package.json'

jobs:
  sort-package-json:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Sort package.json
        run: pnpm run sort:package

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: sorted package.json"
            git push
          else
            echo "No changes detected"
          fi
